### ISSUE TITLE
Getting stuck while extracting pak file

### ISSUE THREAD

**Issue by AlexRingess** [jaszhix/nmsde#2]
**Issue**
I'm getting stuck at 50% while extracting a pak file

**Steps to reproduce**
Trying to open a pak file

![sans titre-1](https://user-images.githubusercontent.com/22620625/29669571-33dfa550-88e4-11e7-9727-ef0be04cf3c6.jpg)

**Comment by xyx0826** [comment]
Similar issue here. Program will stuck at different stages including Decompilation or Extraction when I tried to open PAKs from the game itself or mods. 

I'm on the experimental branch of NMS. However while the program is stuck I can find already unpacked contents in C:\Users\\[USERNAME]\AppData\Roaming\NMSDE\work\MBINs\\[PAKNAME]. They simply seemed not to be recognized (or displayed?) by NMSDE itself.

**Comment by jaszhix** [comment]
Yeah, the implication of this is the non-exml contents are filtered from the PAK when its recompiled, so this will definitely need to be fixed.

**Comment by jaszhix** [comment]
Please let me know if [0.2.0](https://github.com/jaszhix/nmsde/releases/tag/v0.2.0) improves this.

**Comment by xyx0826** [comment]
Awesome. This version has fixed this issue. Good job!

However it seems like when multithreading is enabled, some specific new PAKs opened will not be shown in the window. Restarting the program or opening the PAK again with multithreading disabled will not cause this problem.

The above issue applies to, for example, NMSARC.2E9559C7.pak from the original game files. I have NMS Experimental installed.

**Comment by AlexRingess** [comment]
Yeah ! It is fixed !
Thanks a lot :)

**Comment by jaszhix** [comment]
I did some cleaning up, please let me know if [0.2.0](url) improves this.

**Comment by jaszhix** [comment]
@xyx0826 We can spin this into its own issue. Opened #4
